redis:
  image: redis:latest

mongo:
    image: mongo:latest
    command: --noprealloc --smallfiles
    volumes:
      - "/data/db:/data/db"

web:
  build: .
  volumes:
    - ".:/src"
  links:
    - "mongo:mongo"
    - "redis:redis"
  ports:
    - "5000:5000"